#version: "3"
services:
  installer:
    image: index.docker.io/durancai/staging-installer-web:latest
    container_name: duranc_staging_installer_web
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - /app/output:/app/output
    environment:
      - HOST_IP=${HOST_IP}
      - OUTPUT_BASE=/app/output
    logging:
      options:
        max-size: "10m"
        max-file: "3"
