#!/usr/bin/env bash
# Obfuscated bootstrap wrapper (temp-file exec variant)
# Generated by make-obfuscated-sh.sh
set -euo pipefail

# The generator sets OBF_ENCRYPTED accordingly; for encrypted payloads, provide OBF_PASS at runtime.
: "${OBF_ENCRYPTED:=0}"

# ---- Decoders ----
dec_b64()  { base64 -d; }
dec_gzip() { gzip -dc; }
dec_aes()  { openssl enc -aes-256-cbc -md sha256 -pbkdf2 -d -pass env:OBF_PASS; }

# Extract everything after the payload marker
extract_payload() {
  awk 'f{print} /^__PAYLOAD__$/ {f=1}' "$0"
}

# Run payload from a temp file (NOT via "bash -s")
run_payload() {
  tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
  if [ "${OBF_ENCRYPTED}" = "1" ]; then
    extract_payload | dec_b64 | dec_aes | dec_gzip > "$tmp"
  else
    extract_payload | dec_b64 | dec_gzip > "$tmp"
  fi
  exec /usr/bin/env bash "$tmp" "$@"
}

# Entry
OBF_ENCRYPTED=0

run_payload "$@"
exit 0

__PAYLOAD__
H4sIAAAAAAACA7VX73PaOBD9zl+xdUhJ5opJ0uuH44Z0OHASTxNg+NHcTaeTEbYAN0ZyJRnC5Pq/
35NtwE173wozCVhIu6vdfW8fR68a00g0pkwvKpUjav3SFwyeu9QZ9nvk9T76eL/zemMaeePJ4BDO
OkoKUqnQtI7MghgtIxEtWUyD9vjGpXtO/CmJoyAy8YY0NxQZMpK40KniFMjlkolQEyzF0SOnml6k
JpRrUXtDNbZ+xBu+p5pYRWHE6noZ1Yjh4EymWIZrFsc0mabCpLTiSkdSaLcCl1KZLIRWI9WqEcuA
xQ2NtDdLz7vH/RfZh/wR/w5SnguUp9+78q8nw/bY7/cO4cN7YoGhWRRzShjKMlNySRuZKtKB4kj+
QprKbf/64cq/9VpOY8VsTuaNMFVMBPU828GCB48ulh2bhztb13RJaWKiJaeTSKCcgUTxTknxr2mk
eEhTPpOoDooi15GYox0Un0ppXBj44+xMU4vO39kWSQ3XLo0XkaZE8RUXRlMkZvBheHGGYikTrM7I
LDiFKkJ9CfunSj5y4Vbu/N7DZDD277wWTNNBavXWpWG/P6aBN7zzRyNUizo3XufDr/eFa34ip+pN
/K5DdcHpjD7/aW8uKoQXDxaSHG847A+bedpQyCgxtEy1QdotBIlpUjbZNIg505xS/Ok0lCRV9gUF
AKvr5AafAMTzyiw6SN5+dwndde33rulq0uscps3RmQ9Z65yc0nN2qQzWFGMxbjnVc6e0uNRzLF2U
l0LTqp6EDA3n/Hb8T/14WT8O6fimeXzXPB45p9nO7N8R3Svbl+CtHEMJD6JZFMDOPANZqUSfqqH5
TJ+qWRCfqQq/Dl1eorRbuDllw+1YS1pvreuNNnxJX+BEIMATPMPFqS0soykLHtOkOPcx4ms2BbxX
EWvSXPGEnAK88yR1aIfo3ERx6/kcEKob2u+0AZdDrXw7SD+8c+mu7ffoxmvfjm8OhSE7jixn0XmT
upLrjDj2k4PA6ExtyPaM7X9t3lvYvdpOIaqvyrtfX1Ij5KuGSOO4hMRd15HTGfpjv9O+dcj50UsP
tJFNKZe6OXfZAYchmIpIaAOK5GGBxaN8TAKQCw72nPKAWejaWaq1pdHCZKpTHNts6VYTosYKnuuF
SWYwAN+QANb31PsD3PMkXTRpCNKwOcKwsHYKjs14H9vqtwhZg5ivBxOQtf+SiGPJQnC+zdxaqkcE
+gY78IXiBg2sc6eBDEFmdgDcW2YPEThGkzYhV4pOLi5fn5/a1g9YYqwiYAIFUgqMZfgTgu9PxoPJ
GEAtZRiBZecq3t/++KHT73qt6vtKTqHV3RrV+dcXLIo71es0mnQ63mhkPxer3d2diosA1YJn6sVC
PLuUzsBPj0Kuc9FjL5oKFHPuvmwMv3fVR1PccBZj+ObpHjCtedikXnaPIo06EzMy4SqrHIvL7HxW
4bHmpcCv2v7tZOjtAi95zCYDXKJUhb8rFtkOgxSAqQ6K0Czlxvm/8/3UJKnB1jzvmPy5+9zm2yZN
8vE/YjNuNvlyseUa4q4QB3ttAJ0wF1LZlIYgTQhDnRPrZPAw8qCDuiPUNmCGGomSQaMw8C9B+1Ht
OcFJSEZQfPX89FvtNA+nmJV7E5iYMS5R3UsC57u6v7jsfXvYw2jCdUc54W7D1lCUwFf1eW/6Gzp/
K322Mgfped67wg7nZ15K7DDMBc3ogz8YeF3b7oXo2WueneKBuxzVGQx3Pks+CizbjxbP+/4Yen9Z
sdLO5u3PuqQUUlFHjToC2gghQgeiSnzJ1ZyLYLNVYQgWiJUWH7a5ir51Xfe7OTbaiCAbhcUIK10R
E5aBBZSyWZZ5QTS2l497TzyAJKQ8UdlipsIb258DVFdkkVekMuunNJuZ+JHT9dtZbDO0vOWQkBtw
jJWjm2LUFWrJsQT4H+MDH5R/DQAA

